### ISSUE TITLE
Code isn't visible in Dark Mode

### ISSUE THREAD

**Issue by naveen521kk** [pradyunsg/furo#110]
**Describe the bug**
When I enable dark mode in the browser, using [dark-mode-switcher](https://github.com/rugk/website-dark-mode-switcher/) on Firefox, the code blocks aren't visible.

**To Reproduce**

1. Go to https://pradyunsg.me/furo/kitchen-sink/demo/
2. See the code blocks
3. See error, code blocks not visible.

**Expected behavior**
I would expect the code block to show properly, with proper syntax highlighting.

**Screenshots**
![image](https://user-images.githubusercontent.com/49693820/111985708-f9c51300-8b32-11eb-89ad-043755205dc1.png)
![image](https://user-images.githubusercontent.com/49693820/111985776-15c8b480-8b33-11eb-8e6b-d90aad8621f4.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] FireFox
- Version [e.g. 22] 86.0.1

**Comment by pradyunsg** [comment]
You'll need to take this up with the extension you're using, since that is not handling `<link media="...">` tags:

https://github.com/pradyunsg/furo/blob/1574348b19a857910ebb72947c2c3ed43301dd0d/src/furo/theme/furo/base.html#L57

![Screenshot 2021-03-26 at 6 23 52 PM](https://user-images.githubusercontent.com/3275593/112676528-73753d80-8e60-11eb-90e6-0657948b413f.png)

Firefox 86, on MacOS

**Comment by naveen521kk** [comment]
Ah, extension issue, didn't expect it to happen, but using normal dark mode enabled from system works.

Thanks for your reply.
