### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by hugovk** [pradyunsg/furo#13]
**Is your feature request related to a problem? Please describe.**

Dark mode is the new thing! 

Not only that, they can improve accessibility, ease eye strain, and save battery power.

**Describe the solution you'd like**

Use the `prefers-color-scheme` media query to detect whether the user has requested dark mode, and provide a darker colour scheme.

* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* https://web.dev/prefers-color-scheme/
* https://caniuse.com/?search=prefers-color-scheme

For comparison, see this dark theme issue and PR at the Python Docs Sphinx Theme:

* https://github.com/python/python-docs-theme/issues/43
* https://github.com/python/python-docs-theme/pull/44

**Describe alternatives you've considered**

1. There are Chrome plugins and the like to invert colours, but it's better for the dark colour theme to be chosen manually to make sure there's no odd things. And using a widely-supported media query means it's available for more people.

2. Stick with the bright theme.

**Comment by pradyunsg** [comment]
This is on the cards, and I do plan to add in the prefers-color-scheme media query. The main reason it's not implemented yet is since I'm still figuring out how to handle the customization for it.

Putting an entire set of CSS variables under the dark mode will make it tricky to correctly switch makes it tricky to do things correctly. OTOH, adding dark mode means customization of colours trickier. :)

**Comment by pradyunsg** [comment]
Hmm...

<img width="1440" alt="Screenshot 2020-10-12 at 9 29 24 PM" src="https://user-images.githubusercontent.com/3275593/95767178-0155d580-0cd2-11eb-9d37-c697e48acb1e.png">

**Comment by pradyunsg** [comment]
I'm gonna say 9c1bc1db702edde84ef7e1dda0ad46f09ed7dee6 fixes this. It should be live on the demo docs soon. Open to iterate on this as we go. :)
