### ISSUE TITLE
Wrong rendering for Tables' shadow in light theme

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#183]
### Discussed in https://github.com/pradyunsg/furo/discussions/180

<div type='discussions-op-text'>

<sup>Originally posted by **santiagxf** July  6, 2021</sup>
[snip] table's shadow take 100% of available width even when the table doesn't not. This issue can be seen even in the Furo's documentation page.

![image](https://user-images.githubusercontent.com/32112894/124642034-bb473000-de65-11eb-868f-f9cf2f446ebf.png)
</div>

**Comment by jack1142** [comment]
Is the change to the text alignment (centered instead of aligned to left [as it used to](https://devguide.python.org/triaging/#type)) intentional or is it considered a bug too?

It is not mentioned in this issue but it appears to be related to the same commit that was mentioned as the cause of it in #180.

**Comment by pradyunsg** [comment]
That's a bug from this as well. Turns out I messed this up.

The fix is to add table.align-default styles, so that the table behaves as it used to.

**Comment by pradyunsg** [comment]
Fixed in 4f847461716a7f9cb8a2ac1580466a8f75a50b6a. I'll cut a release in the coming week / next weekend.
