### ISSUE TITLE
Printing on Chrome generates way too many pages

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#358]
### Discussed in https://github.com/pradyunsg/furo/discussions/352

With an empty documentation set, open a generated page in Chrome and try printing the page. Notice that Chrome decides that there are 5 digits (order of 10,000) of pages to print.

**Comment by pradyunsg** [comment]
Also reproducible on https://pradyunsg.me/furo/.

**Comment by berellevy** [comment]
don't know if this detail helps but the issue still exists even when I select the text that I want to print.

my thought is that right clicking selected text and choosing print would send less data to the browser to  but tbh I don't know how print works.

Anyway, hope I was helpfull.

https://github.com/psf/black/issues/2866

**Comment by chapkom** [comment]
I hope this helps.

I ran into this issue on one of my coding projects for work.  It turns out the culprit was a flex styled div that was completely empty.  

It started printing normally once I updated my project to output a non breaking space in the div.

Chrome appears to have some issue rendering flexboxes without inner text for print.

**Comment by pradyunsg** [comment]
This got fixed in #319, which hid one such flexbox-without-inner-text objects. Thanks for providing the context on why this happened in your projects @benjaminpick and @chapkom!

It makes me a bit more comfortable, since your comments provided the missing piece of information I needed to have a better understanding of why #319 fixed this issue. :)
