### ISSUE TITLE
Make the top of page more easily reachable

### ISSUE THREAD

**Issue by dvarrazzo** [pradyunsg/furo#39]
The right-hand-side navigation doesn't have a way to go on top of page.

Example: https://pradyunsg.me/furo/customisation/

By using the right links, you can go at "Theme options" most. If there is a lot of content between Customisation and Theme options you cannot access that section of page via that menu.

Would you feel useful to have "Customisation" there too?

**Comment by pradyunsg** [comment]
Oooooo.

Question: would it being at the same level as the rest of the content be sufficient? Or... Maybe this should have a floating "take me to the top" button instead?

**Comment by dvarrazzo** [comment]
What I had in mind is something at the same level: the first level to be "demoted" to the second ones (the ones currently displayed). I don't think there is the need of adding one level of structure.

While "go to top" would fulfil the same need, the title is more descriptive: it would be the complete summary of the page in the right column.

Using the above link as example:

![image](https://user-images.githubusercontent.com/199429/100407231-bca6b380-305f-11eb-8e68-d5ddcc99618a.png)

**Comment by pradyunsg** [comment]
HMM!

So, what Sphinx gives us is actually a tree that's something like:

- Customisation
  - Theme Options
    - ...
    - ...
    - ...
  - Page specific tweaks
    - ...
  - Custom CSS files

Furo actually has dedicated CSS to specifically hide the top level items, since, well, that's the approach most "ToC tree in the sidebar" documentation themes seem to take. I've not seen anyone add the title of the page there, which makes me a little wary of that idea.

THAT SAID, I do agree that this is a reasonable request (being able to go to top of page).

**Comment by pradyunsg** [comment]
<img width="925" alt="Screenshot 2020-11-27 at 11 04 27 PM" src="https://user-images.githubusercontent.com/3275593/100488234-efef4e00-3104-11eb-8754-1197e8e584aa.png">

Yeeaaa... I'm not sure I can say that this would work well.

**Comment by pradyunsg** [comment]
Maybe a back-to-top arrow beside "contents"?

**Comment by dvarrazzo** [comment]
Why do you think doesn't work?

In my view it's perfect. It's a personal opinion, I'm aware, but I don't see what is wrong in what you have there.

**Comment by pradyunsg** [comment]
I definitely said that based on how it "felt". I guess, more words world be:

- The other headings are "under" the Image heading, and that isn't reflected by this.
- "Image" won't get highlighted by the JS that's used, because Sphinx provides `#` as the URL for the top-level tag, not the actual section ID. :( 
- You'll see the page name in 3 places, with 2 of them being `#` URLs (both in sidebars), which feels like unnecessary/useless redundancy. (yes, useful redundancy is a thing)

But yea, as you say, a lot of this is personal opinion based. It might just be that I don't like any answer to the problem, even though I feel like this is a problem worth solving.

**Comment by dvarrazzo** [comment]
I know that structurally speaking is a lie. However you will have only one of those levels in the page (I know, because in psycopg3 docs I had more than one... and that menu wasn't display correctly :stuck_out_tongue: now I change the docs to reflect the navigation possibilities in furo [1]). So it's not particularly informative to know that the first entry is the first, it's the king, and rules the others:

![image](https://user-images.githubusercontent.com/199429/100490183-6f831a00-3111-11eb-99a9-59cb9d0287ef.png)

Smug title :zipper_mouth_face: It doesn't add much, does it?

About the name repeated in three places, I assume left column, title, right column, right? I think it's not bad:

- left and right column are far away. The repetition is on always under the eye.
- the title will scroll up, leaving the repetitions in the two columns apart
- the page title in the two columns tells two different things:
  - on the left, the position of that title in the whole document
  - on the right, the position of that title within the current page

So I would say that for me is informative repetition :)

[1] If you want to know what I mean you can check out https://github.com/psycopg/psycopg3/commit/8a71e9c3ae36613d2a4c68fb78ceee6b15781250

**Comment by dgw** [comment]
Putting the page title under "contents" like that last screenshot isn't _just_ useless redundancy; it's semantically incorrect. The page doesn't contain itself.

I agree that this problem is worth solving, though. Speaking of not liking any of the answers: What about a floating button that scrolls to the top? Seems to be a fairly common pattern now.

**Comment by pradyunsg** [comment]
> Speaking of not liking any of the answers: What about a floating button that scrolls to the top?

Where do you "float" that button on desktop / tablet / mobile? :P

**Comment by dgw** [comment]
> > Speaking of not liking any of the answers: What about a floating button that scrolls to the top?
> 
> Where do you "float" that button on desktop / tablet / mobile? :P

Same everywhere, lower right corner of the page, on top of everything. I'm on mobile now but can find and share some examples later if you like.

**Comment by dvarrazzo** [comment]
The right column doesn't scroll, so it wouldn't need to float :) 

Still at personal "like/don't like" level, I'm not fond of floating buttons. A "Top :top:" button in the right menu would be a first iteration to fix the problem of having a way to go back to the top of the page. But if you replace the word "top" with the first level title, that's also "a reason" to click on that label.

I don't think that "Customisation" is the title of the page. You can have documents with more than one title at the same level.

```
# Level 1
## Level 2
### Level 3
# Level 1 2
## Level 2 2
...
```

this is alloweds in Sphinx, but furo breaks it. I had to split the docs in several more pages in order to accommodate that (https://github.com/psycopg/psycopg3/commit/ee26c7e0a9e24264ae85e660ae3a614c1d21d6f7) which I was happy to do as furo has just a different style of navigation compared to sphinx.

**Comment by pradyunsg** [comment]
> this is alloweds in Sphinx, but furo breaks it.

Well, it's also semantically wrong to have multiple h1 tags on the same page. :)

> Same everywhere, lower right corner of the viewport, on top of everything.

Fair enough. In that case, this is blocked by ReadTheDocs' embedded version selector. This likely needs to wait until ReadTheDocs' support for that selector becomes better (being discussed in https://github.com/readthedocs/readthedocs.org/pull/8052).

[screenshot showing the RTD version selector in the bottom right corner today]

![Screenshot 2021-04-11 at 12 29 01 PM](https://user-images.githubusercontent.com/3275593/114302580-896e3980-9ac1-11eb-9b6f-78f9f36892bc.png)

**Comment by pradyunsg** [comment]
There's now a "Back to top" button that shows up when you scroll up on the page.

https://user-images.githubusercontent.com/3275593/154657166-df3982f5-e9b8-4486-a5c9-ee9bc88a88cc.mov

Added in 7e0f828b949e950ba7802995b929f0be297a4397.

**Comment by pradyunsg** [comment]
Closing this, since I consider this resolved with the back to top button. It'll be in the next release.
