### ISSUE TITLE
Wrong heading highlighted in contents

### ISSUE THREAD

**Issue by drewyh** [pradyunsg/furo#64]
**Describe the bug**
The wrong heading is highlighted in the contents when selected.

**To Reproduce**
1. Go to [the official documentation for contributing workflow](https://pradyunsg.me/furo/contributing/workflow/)
2. Click on "Documentation Generation"
3. See in "Contents" that "Release process" is highlighted, not "Documentation Generation"

**Expected behavior**
When selected in "Contents", the selected heading should be highlighted.

**Other context**
This seems to occur when a second level heading that cannot be jumped to the top of the screen is selected.

**Comment by pradyunsg** [comment]
This is how all scroll-based TOC highlighting works, AFAIK. It's happening because hitting end-of-page results in highlighting the last element.

We're getting this behaviour from https://github.com/cferdinandi/gumshoe/ so I'd suggest taking this up there. I'm open to suggestions for alternatives to use, that implement the behaviour you're looking for. :)

**Comment by drewyh** [comment]
Right you are. I thought I had seen this work as I described on mkdocs-material, but I've checked there and it behaves the same. This could be closed if you prefer since it seems to be normal.
