### ISSUE TITLE
Option to default navigation tree to expanded

### ISSUE THREAD

**Issue by jreese** [pradyunsg/furo#78]
For sites with a small number of nested navigation elements, I would like to be able to default the trees to being expanded rather than collapsed.

Eg, I have a number of sites with sidebars like this that would benefit from being always expanded (like I get with alabaster):

* Quickstart
* API
  * Topic 1
  * Topic 2
  * Topic 3
* Code of Conduct
* Contributing
* Contact

**Comment by pradyunsg** [comment]
Thanks for filing this issue! Have you tried using Sphinx's `toctree` captions for this instead?

That would let you create a document structure without nesting pages, which might work for you. The only difference is that the "API" page no longer exists, but based on what I've seen, for most projects that's likely fine.

```rst
.. toctree::

    quickstart

.. toctree::
    :caption: API

    topic-1
    topic-2
    topic-3


.. toctree::
    coc
    contributing
    contact
```

I'm actively trying to avoid adding knobs to this theme for catering to everyone's preferences; to keep things simpler (so that this is easy to maintain!) and to nudge users to use all the fancy things that Sphinx gives you. :)

**Comment by pradyunsg** [comment]
Closing due to lack of a response.

**Comment by jreese** [comment]
Sorry for not getting back to this sooner. My biggest issue with using caption is that it no longer looks like a nice, hierarchical header. Compare default collapsed, and expanded, versus using a caption:

<img width="259" alt="Screen Shot 2021-03-06 at 2 38 04 PM" src="https://user-images.githubusercontent.com/6444/110222834-1e11c600-7e8a-11eb-8d7a-fb44a1faf38a.png">
<img width="253" alt="Screen Shot 2021-03-06 at 2 38 11 PM" src="https://user-images.githubusercontent.com/6444/110222836-1eaa5c80-7e8a-11eb-85c0-61b90827419c.png">
<img width="247" alt="Screen Shot 2021-03-06 at 2 38 27 PM" src="https://user-images.githubusercontent.com/6444/110222837-1eaa5c80-7e8a-11eb-92b2-c065d7aa75c0.png">

Combined with #79 being a non-starter, this turns a single 29 line file with headers and autodoc, which results in a clear hierarchy in Alabaster that can navigate to anywhere in one click, into five or more tiny files for Furo that no longer flow together in the resulting site and also require two or more interactions to get anywhere (first to click or expand the "API" header and then again to read the section names and find/click/go to the section you actually care about). This might be useful for written pages and documentation with clearly separation of topics, but adds a lot of overhead (or less visibility) for autodoc-generated content.

And that's a shame, because I really like Furo's theme and support for dark mode, but I'm constantly disappointed by the need to design and structure my content around the theme rather than the theme adapting to the content. Either way, I appreciate the effort you've put into Furo. Cheers.

**Comment by pradyunsg** [comment]
FWIW, you can use multiple `toctree` elements with captions on the page as well:

```
.. toctree::
   :caption: Projects

   blah
   foo
   eggs
   bacon

.. toctree::
   :caption: {anything; or nothing?}

   contributing
   coc
   contact
```

Again, I do think there exists a mechanism in Sphinx's handling of "content trees", that can be used to create the kind of separation you're looking for.

That said, I've filed #95 so that the suggestion I made above works better.
