### ISSUE TITLE
Getting JavaScript not active errors when using Search

### ISSUE THREAD

**Issue by sethmlarson** [pradyunsg/furo#9]
**Describe the bug**

When I use search I receive an error stating: " Please activate JavaScript to enable the search functionality. "

**To Reproduce**

1. Do a search
2. See error

**Expected behavior**

See my search results instead :)

**Screenshots**

https://urllib3.readthedocs.io/en/latest/search.html?q=a&check_keywords=yes&area=default

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox
- Version: 80.0.1

**Comment by pradyunsg** [comment]
Wheeeee! Fixed in 38228f4.

**Comment by sethmlarson** [comment]
Thank you much! :) (and be nice to yourself)

**Comment by domdfcoding** [comment]
I think this has broken again in `2020.11.15b17`. I'm seeing the error on my docs and the demo site. If I pin the version to `2020.11.10b15` it works fine.  

Is this due to e8dc65a7a29a67194d6819bc91f81aa079f1eb0f ?

Examples: 

* https://sphinx-autofixture.readthedocs.io/en/latest/search.html?q=fixture&check_keywords=yes&area=default
* https://pradyunsg.me/furo/search/?q=css&check_keywords=yes&area=default

**Comment by pradyunsg** [comment]
Yup. Looks like something got borked by the `defer`s in the JS. :)

**Comment by pradyunsg** [comment]
93bdea276ad31576cd15489739813bf500485920 should fix this. I'll cut a release now -- @domdfcoding lemme know if stuff works with the beta 18! :)

**Comment by domdfcoding** [comment]
Seems to be working OK with the beta 18. Thanks 😀

**Comment by pradyunsg** [comment]
Awesome! ^>^
